version: '3'
services:
  # Nginx
  nginx-ssl-proxy:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    environment:
      SERVERNAME: scoreboard.h4tt.ca
      EXTRANAMES: healthbiotics.h4tt.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"

  #Healthbiotics
  healthbiotics:
    build:
      context: healthbiotics/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always

networks:
  default:
    external:
      name: ctfd_default
        