version: '3'
services:
  # Nginx
  nginx-ssl-proxy:
    build:
      context: nginx-ssl/
    restart: always
    environment:
      SERVERNAME: scoreboard.h4tt.ca
      EXTRANAMES: healthbiotics.h4tt.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"